<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and judgehost-config.php

// Generated from 'judgehost-static.php.in' on Sun Jun 11 09:03:48 ICT 2017.

define('DOMJUDGE_VERSION', '5.1.3');

define('BINDIR',      '/home/quyenl/domjudge/judgehost/bin');
define('ETCDIR',      '/home/quyenl/domjudge/judgehost/etc');
define('LIBDIR',      '/home/quyenl/domjudge/judgehost/lib');
define('LIBEXTDIR',   '/home/quyenl/domjudge/judgehost/lib/ext');
define('LIBJUDGEDIR', '/home/quyenl/domjudge/judgehost/lib/judge');
define('LOGDIR',      '/home/quyenl/domjudge/judgehost/log');
define('RUNDIR',      '/home/quyenl/domjudge/judgehost/run');
define('TMPDIR',      '/home/quyenl/domjudge/judgehost/tmp');
define('JUDGEDIR',    '/home/quyenl/domjudge/judgehost/judgings');
define('CHROOTDIR',   '/chroot/domjudge');

define('RUNUSER',     'domjudge-run');
define('USE_CGROUPS', '0');

// Possible exitcodes from testcase_run.sh and their meaning.
$EXITCODES = array (
	0   => 'correct',
	101 => 'compiler-error',
	102 => 'timelimit',
	103 => 'run-error',
	104 => 'no-output',
	105 => 'wrong-answer',
//	106 => 'presentation-error', /* dropped since 5.0 */
	107 => 'memory-limit', /* not in use internally */
	108 => 'output-limit',
/* Uncomment the next line(s) to accept internal errors in the judging
 * backend as outcome. WARNING: it is highly discouraged to enable
 * this, as the judgehost may be in an inconsistent state after an
 * internal error occurred and it is recommended to inspect manually.
 */
//	127 => 'internal-error',
//	128 => 'compare-error',
	);
