<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Chủ nhật, 11 Tháng sáu năm 2017 07:40:45 ICT.

define('DOMJUDGE_VERSION', '5.1.3');

define('BINDIR',      '/home/quyenl/domjudge/domserver/bin');
define('ETCDIR',      '/home/quyenl/domjudge/domserver/etc');
define('WWWDIR',      '/home/quyenl/domjudge/domserver/www');
define('LIBDIR',      '/home/quyenl/domjudge/domserver/lib');
define('LIBEXTDIR',   '/home/quyenl/domjudge/domserver/lib/ext');
define('LIBWWWDIR',   '/home/quyenl/domjudge/domserver/lib/www');
define('LIBSUBMITDIR','/home/quyenl/domjudge/domserver/lib/submit');
define('LOGDIR',      '/home/quyenl/domjudge/domserver/log');
define('RUNDIR',      '/home/quyenl/domjudge/domserver/run');
define('TMPDIR',      '/home/quyenl/domjudge/domserver/tmp');
define('SUBMITDIR',   '/home/quyenl/domjudge/domserver/submissions');

define('SUBMITCLIENT_ENABLED', 'yes');

set_include_path(get_include_path() . PATH_SEPARATOR . LIBEXTDIR);
